### PR TITLE
[TS] LPS-18173 MySQL read-write split is hardly using RO datasource

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-18173

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Hi @NorbertKocsis 

About LPS-18173, I want to do some testing.  What methods calls are causing that read transaction issues?

Please, can you tell me the steps you follow in order to test your solution? 

Also, attach that steps to the LPS.

Thank you

**Comment by jorgediaz-lr** [comment]
Closing this pr, because preston has assigned the LPS-18173 in JIRA.

**Pull request closed without merging**
