### PR TITLE
LPS-113813 Register new upgrade for Captcha

### PR DESCRIPTION
**Pull request by martamedio**
Hey @jorgediaz-lr 👋 

I am sending you for review the necessary changes to fix the Captcha related upgrade issue.

Please, check if I've forgotten anything.
Thank you!

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Sent to https://github.com/martamedio/liferay-portal/pull/153

**Pull request closed without merging**
