### PR TITLE
LPS-64232

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
@jorgediaz-lr 

i'll look into the failures

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
first failure passes when run locally

https://gist.github.com/arbetts/9a916cca8a34137b1e3f

**Comment by arbetts** [comment]
second failure happens because we are not mocking the wrong method call in the LocaleUtil test.

**Comment by arbetts** [comment]
the semantic version error is being thrown because of the API change.

you will need to update the versions in the bnd file as well as any module that uses it.

>      [echo] * com.liferay.portal.deploy.hot                      MAJOR      1.0.2      1.0.2      2.0.0      VERSION INCREASE REQUIRED
> 
>      [echo]   >   class      com.liferay.portal.deploy.hot.HookHotDeployListener
> 
>      [echo]       +   method     getLanguageId(java.lang.String)
> 
>      [echo]           +   access     protected
> 
>      [echo]           +   return     java.lang.String
> 
>      [echo]       -   method     getLocale(java.lang.String)
> 
>      [echo]           -   access     protected
> 
>      [echo]           -   return     java.util.Locale

here is an example
https://github.com/brianchandotcom/liferay-portal/pull/37569/commits/498d55eb340becd161af1ab9b123bc8aa808acbb

**Comment by arbetts** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Rebased to last master, added related LPS-64265 and sent to: https://github.com/arbetts/liferay-portal/pull/50

**Pull request closed without merging**
