### PR TITLE
LPS-104178 Configure a non-default mail "from" address to avoid blacklist filtering

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Regression caused by [LPS-84320](https://issues.liferay.com/browse/LPS-84320)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hi @Jorgediaz-lr. It's in my local environment. Should your fix not apply there also? My build is from 2019/10/28.

I don't think I saw this particular failure in CI testing. I'll test on my fork and let you know.

**Comment by stian-sigvartsen** [comment]
HI @jorgediaz-lr . Looks like your fix handles it fine stian-sigvartsen/liferay-portal/pull/206
Thanks!

**Comment by jorgediaz-lr** [comment]
Hi @stian-sigvartsen 

Thank you for the information.

I am going to execute tests in a clean local environment and in case I reproduce it, I will try applying same solution than original https://issues.liferay.com/browse/LPS-101178

**Comment by jorgediaz-lr** [comment]
I was able to reproduce the issue in local environments in case you have "test@liferay.com" as default email.

To avoid this, I am setting email in SynchronousMailTestRule, see: https://github.com/shuyangzhou/liferay-portal/pull/8689

CI tests are not affected as they have their custom portal-ext.properties

**Pull request closed without merging**
